-- MySQL Script generated by MySQL Workbench
-- Tue Dec 19 21:06:46 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tbl_Member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_Member` (
  `member_id` INT NOT NULL AUTO_INCREMENT,
  `member_email` VARCHAR(200) NOT NULL,
  `member_first_name` VARCHAR(100) NOT NULL,
  `member_last_name` VARCHAR(100) NOT NULL,
  `member_created_time` DATE NOT NULL,
  `member_update_time` DATETIME NOT NULL,
  `member_phone_number` VARCHAR(10) NOT NULL,
  `member_password` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`member_id`),
  UNIQUE INDEX `email_UNIQUE` (`member_email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_Movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_Movie` (
  `movie_id` INT NOT NULL AUTO_INCREMENT,
  `movie_name` VARCHAR(100) NOT NULL,
  `movie_time` INT NOT NULL,
  `movie_description` VARCHAR(1000) NULL,
  `movie_update_time` DATETIME NOT NULL,
  `movie_image` VARCHAR(250) NOT NULL,
  `movie_type` INT NOT NULL,
  PRIMARY KEY (`movie_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_Meal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_Meal` (
  `meal_id` INT NOT NULL AUTO_INCREMENT,
  `meal_name` VARCHAR(100) NOT NULL,
  `meal_price` INT NOT NULL,
  `meal_description` VARCHAR(1000) NULL,
  `meal_update_time` DATETIME NOT NULL,
  `meal_image` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`meal_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_Manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_Manager` (
  `manager_id` INT NOT NULL AUTO_INCREMENT,
  `manager_first_name` VARCHAR(100) NOT NULL,
  `manager_last_name` VARCHAR(100) NOT NULL,
  `manager_phone_number` VARCHAR(10) NOT NULL,
  `manager_email` VARCHAR(100) NOT NULL,
  `manager_password` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`manager_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_Room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_Room` (
  `room_id` INT NOT NULL AUTO_INCREMENT,
  `room_name` VARCHAR(100) NOT NULL,
  `room_price` INT NOT NULL,
  `room_description` VARCHAR(1000) NULL,
  `room_update_time` DATETIME NOT NULL,
  `room_image` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`room_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_Order` (
  `older_id` INT NOT NULL AUTO_INCREMENT,
  `member_id` INT NOT NULL,
  `movie_id` INT NOT NULL,
  `room_id` INT NOT NULL,
  `older_date` DATE NOT NULL,
  `older_total_price` INT NOT NULL,
  `older_time_of_day` INT NOT NULL,
  `order_datetime` DATETIME NOT NULL,
  `older_status` INT NOT NULL,
  PRIMARY KEY (`older_id`),
  INDEX `order_member_id_fk_idx` (`member_id` ASC) VISIBLE,
  INDEX `order_movie_id_fk_idx` (`movie_id` ASC) VISIBLE,
  INDEX `order_room_id_fk_idx` (`room_id` ASC) VISIBLE,
  CONSTRAINT `order_member_id_fk`
    FOREIGN KEY (`member_id`)
    REFERENCES `mydb`.`tbl_Member` (`member_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `order_movie_id_fk`
    FOREIGN KEY (`movie_id`)
    REFERENCES `mydb`.`tbl_Movie` (`movie_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `order_room_id_fk`
    FOREIGN KEY (`room_id`)
    REFERENCES `mydb`.`tbl_Room` (`room_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_Order_Meal_Linking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_Order_Meal_Linking` (
  `order_id` INT NOT NULL,
  `meal_id` INT NOT NULL,
  `omlinking_price` INT NOT NULL,
  `omlinking_serving` INT NOT NULL,
  INDEX `linking_order_id_fk_idx` (`order_id` ASC) VISIBLE,
  INDEX `linking_meal_id_fk_idx` (`meal_id` ASC) VISIBLE,
  CONSTRAINT `linking_order_id_fk`
    FOREIGN KEY (`order_id`)
    REFERENCES `mydb`.`tbl_Order` (`older_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `linking_meal_id_fk`
    FOREIGN KEY (`meal_id`)
    REFERENCES `mydb`.`tbl_Meal` (`meal_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_manager_room_linking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_manager_room_linking` (
  `manager_id` INT NOT NULL,
  `room_id` INT NOT NULL,
  INDEX `linking_manager_id_fk_idx` (`manager_id` ASC) VISIBLE,
  INDEX `linking_room_id_fk_idx` (`room_id` ASC) VISIBLE,
  CONSTRAINT `linking_manager_id_fk`
    FOREIGN KEY (`manager_id`)
    REFERENCES `mydb`.`tbl_Manager` (`manager_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `linking_room_id_fk`
    FOREIGN KEY (`room_id`)
    REFERENCES `mydb`.`tbl_Room` (`room_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_manager_movie_linking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_manager_movie_linking` (
  `manager_id` INT NOT NULL,
  `movie_id` INT NOT NULL,
  INDEX `linking_manager_id_fk_idx` (`manager_id` ASC) VISIBLE,
  INDEX `linking_movie_id_fk_idx` (`movie_id` ASC) VISIBLE,
  CONSTRAINT `linking_manager_id_fk`
    FOREIGN KEY (`manager_id`)
    REFERENCES `mydb`.`tbl_Manager` (`manager_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `linking_movie_id_fk`
    FOREIGN KEY (`movie_id`)
    REFERENCES `mydb`.`tbl_Movie` (`movie_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_manager_member_linking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_manager_member_linking` (
  `manager_id` INT NOT NULL,
  `member_id` INT NOT NULL,
  INDEX `linking_manager_id_fk_idx` (`manager_id` ASC) VISIBLE,
  INDEX `linking_member_id_fk_idx` (`member_id` ASC) VISIBLE,
  CONSTRAINT `linking_manager_id_fk`
    FOREIGN KEY (`manager_id`)
    REFERENCES `mydb`.`tbl_Manager` (`manager_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `linking_member_id_fk`
    FOREIGN KEY (`member_id`)
    REFERENCES `mydb`.`tbl_Member` (`member_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_manager_order_linking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_manager_order_linking` (
  `manager_id` INT NOT NULL,
  `order_id` INT NOT NULL,
  INDEX `linking_manager_id_fk_idx` (`manager_id` ASC) VISIBLE,
  INDEX `linking_order_id_fk_idx` (`order_id` ASC) VISIBLE,
  CONSTRAINT `linking_manager_id_fk`
    FOREIGN KEY (`manager_id`)
    REFERENCES `mydb`.`tbl_Manager` (`manager_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `linking_order_id_fk`
    FOREIGN KEY (`order_id`)
    REFERENCES `mydb`.`tbl_Order` (`older_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_manager_meal_linking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_manager_meal_linking` (
  `manager_id` INT NOT NULL,
  `meal_id` INT NOT NULL,
  INDEX `linking_manager_id_fk_idx` (`manager_id` ASC) VISIBLE,
  INDEX `linking_meal_id_fk_idx` (`meal_id` ASC) VISIBLE,
  CONSTRAINT `linking_manager_id_fk`
    FOREIGN KEY (`manager_id`)
    REFERENCES `mydb`.`tbl_Manager` (`manager_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `linking_meal_id_fk`
    FOREIGN KEY (`meal_id`)
    REFERENCES `mydb`.`tbl_Meal` (`meal_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
